
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blog

test:
  <<: *default
  database: blog_tst

production:
  <<: *default
  database: blog